apiVersion: v1
kind: Pod
metadata:
  name: secrets-nginx
spec:
  containers:
  - name: envars-test-container
    image: nginx
    env:
      - name: my_password_here
        value: "{aqua.testing123}"
